workflowVersion: 1.0.0
speakeasyVersion: latest
sources:
    Polar-OAS:
        inputs:
            - location: https://api.polar.sh/openapi.json
        overlays:
            - location: .speakeasy/security.overlay.yml
            - location: .speakeasy/type_parameter.overlay.yml
        registry:
            location: registry.speakeasyapi.dev/polar/polar/polar-oas
targets:
    polar:
        target: python
        source: Polar-OAS
        codeSamples:
            output: codeSamples.yaml
